version: "3"

services:
  mongo:
    container_name: mongo-db
    image: mongo
    ports:
      - 27017:27017
    networks:
      - shared-network
    volumes:
      - mongo-data:/data/db

  backend:
    container_name: app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - JWT_SECRET=somerandomsecretkey
      - MONGO_URI=mongodb://mongo-db:27017/start-db
    ports:
      - 8080:8080
    networks:
      - shared-network
    depends_on:
      - mongo

  frontend:
    container_name: app-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    stdin_open: true
    tty: true
    networks:
      - shared-network
    depends_on:
      - backend

networks:
  shared-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local
